Add the quicklz package
RT-Thread-packages/quicklz pull request #1
Opened 2018-02-04 01:48 UTC by chenyong111

2018-02-04 02:24 UTC, BernardXiong commented
Please provide README, doc, example.

2018-02-04 09:39 UTC, chenyong111 commented
如果示例中要包含compress需要至少270K的ROM（我们现在只用到了decompress），示例中需要包含compress吗？

2018-02-04 09:41 UTC, chenyong111 commented
如果示例中要包含compress需要至少270K的RAM（我们现在只用到了decompress），示例中需要包含compress吗？

2018-02-06 03:43 UTC, armink requested changes

2018-02-06 03:43 UTC, armink commented on quicklz_sample.c
> +        rt_kprintf("[qlz] input argc : %d error , the correct input format sample(qlz_test -c(-d) /file.txt /file.d.txt)!\n", argc);
把压缩与解压命令格式分两行写会不会更加直观

2018-02-06 03:43 UTC, armink commented on README.md
> +QuickLZ是世界上速度最快的压缩库，速度可达到单核308 Mbyte/s， 使用简单，易于集成。这个 [quicklz](https://github.com/RT-Thread-packages/quicklz) 库是RT-thread针对官方[qiuicklz](http://www.quicklz.com/download.html)的C库的移植， 有关quicklz的更多信息，请参阅
> QuickLZ是世界上速度最快的压缩库

QuickLZ **号称** 是世界上速度最快的压缩库

2018-02-06 03:43 UTC, armink commented on README.md
> +  menuconfig package path：`RT-Thread online package/miscellaneous package/QucikLZ`
总感觉路径中间有空格后，理解有歧义，改为下面的方式会不会更好理解

`RT-Thread online package`->`miscellaneous package`->`QucikLZ`

2018-02-06 03:43 UTC, armink commented on README.md
> +menuconfig path：`RT-Thread online package/miscellaneous package/QucikLZ/Enable using quizklz sample`；
这里的换行符显示没有生效，增加些空行

2018-02-06 03:43 UTC, armink commented on README.md
> +配置压缩等级选项，配置为level 1（有三种等级 1 2 3，level 1 压缩速度最快，压缩比最小，level 3 压缩速度最快，压缩比最大）。
> 有三种等级 1 2 3

有三种等级：1/2/3

2018-02-06 03:43 UTC, armink commented on README.md
> +使用方式：msh cmd `qlz_test -c /file.bin /file.cmprs.bin` `qlz_test -d /file.cmprs.bin /file_dcmprs.bin`
上面增加空行

2018-02-06 04:22 UTC, armink requested changes

2018-02-06 04:22 UTC, armink commented on README.md
> +  menuconfig package path：`RT-Thread online package -> miscellaneous package -> QucikLZ`
`RT-Thread online package`->`miscellaneous package`->`QucikLZ`

2018-02-06 04:22 UTC, armink commented on README.md
> +menuconfig path：`RT-Thread online package/miscellaneous package/QucikLZ/Enable using quizklz sample`；
`RT-Thread online package`->`miscellaneous package`->`QucikLZ`

2018-02-06 04:22 UTC, armink commented on README.md
> +menuconfig path：`RT-Thread online package/miscellaneous package/QucikLZ/Enable using quizklz sample`；
重新完善下

2018-02-06 05:13 UTC, armink approved these changes

2018-02-06 06:20 UTC, merged